
CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL
);
CREATE TABLE Room (
  id SERIAL PRIMARY KEY,
  code VARCHAR(6) UNIQUE NOT NULL,
  members INTEGER DEFAULT 0
);



CREATE TABLE Message (
    id SERIAL PRIMARY KEY,
    content VARCHAR(200),
    room_id INTEGER NOT NULL,
    FOREIGN KEY (room_id) REFERENCES Room(id)
);
