CREATE TABLE Users (
  UserID SERIAL PRIMARY KEY,
  firstName VARCHAR NOT NULL,
  lastName VARCHAR NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE Room (
  id SERIAL PRIMARY KEY,
  code VARCHAR(6) UNIQUE NOT NULL,
  members INTEGER DEFAULT 0,
  FOREIGN KEY (room_id) REFERENCES Message(room_id)
);

CREATE TABLE Message (
    id SERIAL PRIMARY KEY,
    content VARCHAR(200),
    room_id INTEGER NOT NULL,
    FOREIGN KEY (room_id) REFERENCES Room(id)
);